### ISSUE TITLE
Find<T> 

### ISSUE THREAD

**Issue by jwvg0425** [pjc0247/GameObjectExt.unity#1]
이거 타입 T 제약 조건 MonoBehaviour 말고 Component로 바꾸는 게 낫지 않을까요

지금 이거 잘 쓰고 있는데 `"Background".Find<SpriteRenderer>()` 이런게 안 돼서 불편해가지고 Component로 제약 조건 바꿔서 쓰고 있는데 이게 더 편한 거 같음

**Comment by pjc0247** [comment]
오 사실 나도 로컬에선 그렇게 바꿔스고잇는데 커밋을안함

**Comment by pjc0247** [comment]
https://github.com/pjc0247/GameObjectExt.unity/commit/8c68a913debb7f2d512a6529a260269dd5fc1d65

**Comment by jwvg0425** [comment]
good

**Comment by jwvg0425** [comment]
근데 이거 진짜 편한거같음 개 좋음

**Comment by pjc0247** [comment]
민수가꿈에나와서알려줌

**Comment by jwvg0425** [comment]
갓민수..
